#!/bin/bash

echo "🧹 Script pour nettoyer la session Google..."
echo ""
echo "Pour forcer Google à vous demander de choisir un compte :"
echo ""
echo "1. Ouvrez Chrome"
echo "2. Allez sur : chrome://settings/content/all"
echo "3. Cherchez 'google.com'"
echo "4. Cliquez sur la poubelle pour supprimer tous les cookies Google"
echo ""
echo "OU"
echo ""
echo "1. Allez sur https://accounts.google.com"
echo "2. Déconnectez-vous de tous les comptes"
echo "3. Fermez complètement Chrome"
echo "4. Rouvrez Chrome"
echo ""
echo "Ensuite :"
echo "1. Rechargez votre extension (chrome://extensions)"
echo "2. Essayez de vous connecter avec Google"
echo ""
echo "✅ Google devrait maintenant vous demander de choisir un compte!"