services:
  # Service Web (API)
  - type: web
    name: lexiflow-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: lexiflow-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://lexiflow.com
      - key: PORT
        value: 10000

# Base de données PostgreSQL
databases:
  - name: lexiflow-db
    plan: free
    ipAllowList: []